### ISSUE TITLE
Gradle Compilation error:variable internal_static_hstream_server_CommandPushQuery_descriptor

### ISSUE THREAD

**Issue by cb1980s** [hstreamdb/hstreamdb-java#13]
I download the latest updates for compiling,but eclipse report error the following:
        E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:79: error: cannot find symbol
    return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_descriptor;
                                  ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_descriptor
  location: class HStreamProto
E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:85: error: cannot find symbol
    return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_fieldAccessorTable
                                  ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_fieldAccessorTable
  location: class HStreamProto
E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:291: error: cannot find symbol
      return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_descriptor;
                                    ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_descriptor
  location: class HStreamProto
E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:297: error: cannot find symbol
      return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_fieldAccessorTable
                                    ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_fieldAccessorTable
  location: class HStreamProto
E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:328: error: cannot find symbol
      return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_descriptor;
                                    ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_descriptor
  location: class HStreamProto
5 errors

    What's wrong?Maybe hstream.proto file is not be updated.Looking forward to your reply.

**Comment by daleiz** [comment]
Do you use code in main brach? 
If so, please update to the latest commit.
I recommend that you should use the release versions (which already published on maven center), because the code for the main branch changes frequently.

**Comment by cb1980s** [comment]
@daleiz,yes.I made the latest updates and recompile it,but the issue still re-occured.

Working Directory: E:\Downloads\hstreamdb-java-main\hstreamdb-java-main
Gradle User Home: E:\Gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 7.0.2
Java Home: D:\JDK\jdk-16.0.2
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: true
Offline Mode Enabled: false
Gradle Tasks: assemble

> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto UP-TO-DATE

> Task :compileJava
E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:79: error: cannot find symbol
    return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_descriptor;
                                  ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_descriptor
  location: class HStreamProto
E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:85: error: cannot find symbol
    return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_fieldAccessorTable
                                  ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_fieldAccessorTable
  location: class HStreamProto
E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:291: error: cannot find symbol
      return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_descriptor;
                                    ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_descriptor
  location: class HStreamProto
E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:297: error: cannot find symbol
      return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_fieldAccessorTable
                                    ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_fieldAccessorTable
  location: class HStreamProto
E:\Downloads\hstreamdb-java-main\hstreamdb-java-main\build\generated\source\proto\main\java\io\hstream\CommandPushQuery.java:328: error: cannot find symbol
      return io.hstream.HStreamProto.internal_static_hstream_server_CommandPushQuery_descriptor;
                                    ^
  symbol:   variable internal_static_hstream_server_CommandPushQuery_descriptor
  location: class HStreamProto
5 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
4 actionable tasks: 1 executed, 3 up-to-date

**Comment by cb1980s** [comment]
@daleiz,I used hstreamdb-java-0.2.0.jar,it does not meet my requirements.So I need to recompile main branch to generate new jar file.Unfortunately,some of main brach coding may be update completely.The most possible file is hstream.proto according to eclipse gradle compilation error.
      @daleiz ,you should compile main brach,take a look at it and check whether it is complete.By the way,I succeeded in compiling v0.2.0 main brach and generating hstreamdb-java-0.2.0.jar.

**Comment by cb1980s** [comment]
@daleiz ,Sorry,I completely downloaded main branch and compile successfully.You are right.
