### ISSUE TITLE
The latest report after testing v0.3.0(progress,issue and expectation)

### ISSUE THREAD

**Issue by cb1980s** [hstreamdb/hstreamdb-java#18]
Dear @daleiz:
     I have tested v0.3.0,and I now report issues and my expectations:
 Progress
    query view now works fine.I can now create view and query view successfully.Thanks to all contributors.
    By the way,please make page updates about "create view" and "select view"

 Issue 1: Stream query does not work
    Exception Info: 
    Exception in thread "main" java.lang.IllegalStateException: Expected the service QueryerImpl [FAILED] to be RUNNING, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:345)
	at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:281)
	at com.geostar.hstream.StreamQuery.main(StreamQuery.java:111)
Caused by: io.grpc.StatusRuntimeException: CANCELLED: Cancelled
    coding:
        Observer<HRecord> observer =
		      new Observer<HRecord>() {
		        @Override
		        public void onNext(HRecord value) {
		          System.out.println(value);
		        }

		        @Override
		        public void onError(Throwable t) {
		          System.out.println("error happend!");
		        }

		        @Override
		        public void onCompleted() {}
		      };

		// second, create a queryer to execute a sql 
		Queryer queryer =
		      client
		          .newQueryer()
		          .sql("select * from "+TEST_STREAM+" emit changes;")
		          .resultObserver(observer)
		          .build();

		// third, start the queryer 
		queryer.startAsync().awaitRunning();
			   // client.close();

       Issue 2: consume record does not work fine
         coding:
                HStreamClient client = HStreamClient.builder().serviceUrl(SERVICE_URL).build();
	        
	        Subscription subscription =
	                Subscription.newBuilder()
	                        .setSubscriptionId(TEST_SUBSCRIPTION)
	                        .setStreamName(TEST_STREAM)
	                        .setOffset(
	                                SubscriptionOffset.newBuilder().setSpecialOffset(SubscriptionOffset.SpecialOffset.EARLIST)
	                                        .build())
	                        .build();
	        client.createSubscription(subscription);
			
	        Consumer consumer = client.newConsumer()
	                .subscription(TEST_SUBSCRIPTION)
	                .hRecordReceiver((receivedHRecord, responder) -> {
	                    System.out.println("get record: " + receivedHRecord.getRecordId());
	                })
	                .build();
	       consumer.startAsync().awaitRunning();
	       
	    }
           Exception Info:
              8月 16, 2021 3:11:24 下午 io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed@4c85e75b
io.hstream.HStreamDBClientException$ConsumerException: send heartbeat error
	at io.hstream.impl.ConsumerImpl$1.onError(ConsumerImpl.java:67)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Can't send hearbeat to an unsubscribed stream.
	at io.grpc.Status.asRuntimeException(Status.java:534)
	... 10 more

          get record: batchId: 8589934593
 
           get record: batchId: 8589934594

           get record: batchId: 8589934595              
    
   Issue 3: Sink connector does not work fine 
        Sink connector can not write stream data into mysql table.
       

   My expectations:
      1.Except consumer,how to query all records not the latest(emit changes)?
      2.Consuming records,how to set position in stream except EARLIEST and LATEST?
      3.Source connector can be supported(both elasticsearch and mysql).
    
      @daleiz,do you have schedule to accomplish the above?

**Comment by cb1980s** [comment]
Looking forward to your reply.Thanks again.

**Comment by daleiz** [comment]
@cb1980s 
I just updated [examples](https://github.com/daleiz/hstreamdb-java-example).
 For your issue1 and issue2，you can try [examples](https://github.com/daleiz/hstreamdb-java-example).

Note that you should use hstreamdb-java v0.3.0 and hstreamdb server v0.5.2 .

**Comment by cb1980s** [comment]
@daleiz,thanks. It's my hope that the other issues  can be fixed soon.

**Comment by daleiz** [comment]
@cb1980s 
For your issue 3, we will write a tutorial about  how to use connector.

**Comment by daleiz** [comment]
> 1.Except consumer, how to query all records not the latest(emit changes)?

Do you want sql like this `` select ... from ... where offset > EARLIST emit changes`` ?

**Comment by daleiz** [comment]
>  2.Consuming records,how to set position in stream except EARLIEST and LATEST?

like this:
```java

 Subscription subscription1 =
        Subscription.newBuilder()
            .setSubscriptionId(DEMO_SUBSCRIPTION)
            .setStreamName(DEMO_STREAM)
            .setOffset(
                SubscriptionOffset.newBuilder()
                    .setRecordOffset(RecordId.newBuilder().setBatchId(1).setBatchIndex(0).build())
                    .build())
            .build();

```

**Comment by daleiz** [comment]
>  3.Source connector can be supported(both elasticsearch and mysql)

This is scheduled.

**Comment by daleiz** [comment]
@cb1980s 
You can follow this tutorial for usage of mysql sink connector.

**Comment by cb1980s** [comment]
Thank you,@daleiz.Let me try a test and report.

**Comment by cb1980s** [comment]
I will reopen a new thread to report test result
