### ISSUE TITLE
Latest test report

### ISSUE THREAD

**Issue by cb1980s** [hstreamdb/hstreamdb-java#27]
@daleiz,I have tested all feataures of hstreamdb-java module.Now I report the issues as following:
  1) StreamQuery can successfully query stream's emit changes,but callback class Observer reports "error happend"
  2) The latest version does not support   accurate position of stream  except "EARLIEST,LATEST".
  3) Mysql sink connector does not work fine.Stream data does not write data into mysql(5.7.35) table,connector's status shows "TASK_CONNECTION_ABORT",create statement as following:
      create sink connector mysql_conn WITH (TYPE=mysql,stream=test_stream,host="192.168.101.11",port=3306,username="c",password="c",database="c");

**Comment by cb1980s** [comment]
![image](https://user-images.githubusercontent.com/88361293/132657767-4812b819-8000-4629-96ed-8ec1c95fc9c6.png)

**Comment by cb1980s** [comment]
insert 10000 hrecords to stream 'test_stream',it succeeded:
![image](https://user-images.githubusercontent.com/88361293/132662200-681a8ae4-a6a0-4e1a-88a8-0d65876aa723.png)

**Comment by cb1980s** [comment]
Sink connector 'mysql_conn' does not create mysql table 'test_stream' :

![image](https://user-images.githubusercontent.com/88361293/132662339-5ae19882-966f-4e5a-abf1-15b9e48850b7.png)

**Comment by daleiz** [comment]
> StreamQuery can successfully query stream's emit changes,but callback class Observer reports "error happend"

Please provide error details.

**Comment by daleiz** [comment]
> The latest version does not support accurate position of stream except "EARLIEST,LATEST".

fixed, try v0.5.0-SNAPSHOT

**Comment by cb1980s** [comment]
@daleiz,thanks
