### ISSUE TITLE
About the usage of hstreamdb-java(3 Issues)

### ISSUE THREAD

**Issue by cb1980s** [hstreamdb/hstreamdb-java#6]
During using hstreamdb-java,I encountered some issues below:
    Issue 1: Failed to create subscription:
     public class CreateSubscription {
	private static final String serviceUrl = "127.0.0.1:6570";
	private static final String TEST_STREAM = "test_stream";
	private static final String TEST_SUBSCRIPTION = "abcc";
	
	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		HStreamClient client = HStreamClient.builder().serviceUrl(serviceUrl).build();
		
		
		Subscription subscription = Subscription.newBuilder().setStreamName(TEST_STREAM).
				setSubscriptionId(TEST_SUBSCRIPTION).build();
	
		
		client.createSubscription(subscription);
		client.close();
	}

}
Run it at the first time,eclipse reported:
     Exception in thread "main" io.grpc.StatusRuntimeException: CANCELLED: Cancelled
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.hstream.HStreamApiGrpc$HStreamApiBlockingStub.createSubscription(HStreamApiGrpc.java:746)
	at io.hstream.impl.ClientImpl.createSubscription(ClientImpl.java:97)
Re-run again,eclipse reported:
        Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: SubscriptionId has been used.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.hstream.HStreamApiGrpc$HStreamApiBlockingStub.createSubscription(HStreamApiGrpc.java:746)
	at io.hstream.impl.ClientImpl.createSubscription(ClientImpl.java:97)

Issue 2:How to do consuming operation:
       I tried Producer to write rawrecord or hrecord into hstreamdb,it works fine.
      
      private static final String serviceUrl = "127.0.0.1:6570";
	private static final String TEST_STREAM = "test_stream";
	private static final String TEST_SUBSCRIPTION = "test_subscription";
	
	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		HStreamClient client = HStreamClient.builder().serviceUrl(serviceUrl).build();
		Consumer consumer = client.newConsumer()
		        .subscription(TEST_SUBSCRIPTION).hRecordReceiver(new HRecordReceiver() {
					@Override
					public void processHRecord(ReceivedHRecord arg0, Responder arg1) {
						// TODO Auto-generated method stub
						
					}
		        	
		        })
		        .build();
		 consumer.startAsync();
 		 client.close();
		 
	}        
       The above coding do nothing while I am inserting hrecords into hstreamdb.Why?What is wrong?

 Issue3:The clause "emit changes" only query the real-time data,how to query all exsiting data?such as database mysql.

     Any help will be appericated,thanks.

**Comment by cb1980s** [comment]
Just now I found another issue about ClientImpl's method stremQuery.I coding the following,but it do nothing although another jvm is inserting hrecord into stream 'test_stream'.What 's wrong?
        
        private static final String serviceUrl = "127.0.0.1:6570";
	private static final String TEST_STREAM = "test_stream";
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		HStreamClient client = HStreamClient.builder().serviceUrl(serviceUrl).build();
		Publisher<HRecord> publisher = client.streamQuery("select * from "+TEST_STREAM+" emit changes;");
		
		Observer<HRecord> observer = new Observer<HRecord>() {
		    @Override
		    public void onNext(HRecord hrecord) {
		        System.out.println(hrecord);
		    }

		    @Override
		    public void onError(Throwable t) {
		        throw new RuntimeException(t);
		    }

		    @Override
		    public void onCompleted() {

		    }
		};

		publisher.subscribe( observer);
		
	}
  
   Any help will be appericated.

**Comment by cb1980s** [comment]
After  learned from  the page(https://github.com/daleiz/hstreamdb-java-example),I solved issue1 and issue2.But the issue3 and issue4(streamQuery) are not solved yet.Thanks to daleiz.

**Comment by daleiz** [comment]
For your issue3:
```
Issue3:The clause "emit changes" only query the real-time data,
how to query all exsiting data?such as database mysql.
```
Currently, the streamQuery can only see the data received after the query started. Later we will support letting the user specify the starting offset of the stream in the query.

**Comment by daleiz** [comment]
For your issue4, I think the reason is that the query has not been started completely when ``publisher.subscribe( observer)`` returned, and you can try waiting a few seconds  for the query to start completely before beginning to write data(refering to the following code).

https://github.com/hstreamdb/hstreamdb-java/blob/17f4783bc47329a18a9f2198c6aa3eb2463f710a/src/test/java/io/hstream/HStreamClientTest.java#L224

The current ``streamQuery `` related interfaces do tend to be confusing, and I will refactor it later.
Thanks for your feeback @cb1980s .

**Comment by daleiz** [comment]
Also, @cb1980s  I suggest that you can open multiple github issues for different problems.

**Comment by cb1980s** [comment]
@daleiz ,thank you very much.In order to verify hstreamdb's feasibility and usability,I am now testing it.So I will report issues timely.
With your help,the issue1,issue2 and issue4 are solved. Looking forward to re-test issue4.Thank you again.
