### ISSUE TITLE
About sink connector

### ISSUE THREAD

**Issue by cb1980s** [hstreamdb/hstreamdb-java#7]
According to user manual page(https://docs.hstream.io/sql/statements/create-connector/),I verified "create connector" command.
     I installed mysql 8.0 and hstreamdb docker on my linux virtual machine,everything works fine.I tried to create a sink connector associated with mysql 8.0,but failed.HStreamdb client report the following:
    > CREATE SINK CONNECTOR  mysql_conn WITH(TYPE=mysql,stream=test_stream,host="192.168.2.2",port=3306,username="test",password="test",database="test");
Client Error: ClientIOError (GRPCIOBadStatusCode StatusCancelled (StatusDetails {unStatusDetails = "Cancelled"}))
     
    I tried mysql5.7,connector created successfully.But no table is created  in mysql database 'test',no record is written too.Why?What's wrong with my usage?

**Comment by Time-Hu** [comment]
1. The version of MySQL is restricted to 5.X
2. You do need to create the table first to accommodate the current implementation.

The improvements of connectors are scheduled.

**Comment by cb1980s** [comment]
Looking forward to test changes.
