### ISSUE TITLE
About view's query

### ISSUE THREAD

**Issue by cb1980s** [hstreamdb/hstreamdb-java#8]
I coded the following and run it.At the same time,I create a view based on the steam .
    HStreamClient client = HStreamClient.builder().serviceUrl(serviceUrl).build();
		Producer producer = client.newProducer()
				.stream(TEST_STREAM)
				.enableBatch()
				.recordCountLimit(1000)
				.build();

		for(int c = 0; c < 1000000;c++) {
			HRecord hRecord = HRecord.newBuilder()
					.put("key1", c % 2)
					.put("key2", String.format("hello_%020d", c))
					.put("key3", c %2 == 0?true:false)
					.build();
			//write aysnc
			//producer.writeAsync(hRecord);
			//write sync
			producer.write(hRecord);
			if((c % 1000) == 0 &&  c > 0) {
				System.err.println("=======================================>"+c);
			}
		}
		producer.flush();
		client.close();
    
     In hstream-client docker container,run the following command:
        create view test_stream_v as select key1,key2,key3,SUM(key1) from test_stream group by key1 emit changes;
      But query test_stream_v with the following command,I got nothing: 
          select * from test_stream_v where key1 = 1;
          Done. No results.

    Why?What's wrong?

**Comment by daleiz** [comment]
It is a bug, mainly due to a problem with the internal handling of number types, and we are fixing it. 
For your example, you could try making ``key1`` be a string.

**Comment by cb1980s** [comment]
ok.let me try 0.3.0.
